name: myapp

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/page-1/images/image-9.png
    - assets/page-1/images/image-46.png
    - assets/page-1/images/image-42.png
    - assets/page-1/images/image-34.png
    - assets/page-1/images/image-40.png
    - assets/page-1/images/image-9-eAQ.png
    - assets/page-1/images/image-24.png
    - assets/page-1/images/image-17.png
    - assets/page-1/images/image-9-qA4.png
    - assets/page-1/images/image-51.png
    - assets/page-1/images/image-46-ACL.png
    - assets/page-1/images/image-23-bg.png
    - assets/page-1/images/image-48.png
    - assets/page-1/images/image-5.png
    - assets/page-1/images/image-49.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/image-33.png
    - assets/page-1/images/image-24-MDN.png
    - assets/page-1/images/image-32.png
    - assets/page-1/images/image-57.png
    - assets/page-1/images/image-42-iFW.png
    - assets/page-1/images/image-29.png
    - assets/page-1/images/image-23.png
    - assets/page-1/images/image-69.png
    - assets/page-1/images/image-42-xvx.png
    - assets/page-1/images/image-66.png
    - assets/page-1/images/image-53.png
    - assets/page-1/images/image-134.png
    - assets/page-1/images/image-40-ieG.png
    - assets/page-1/images/group-1.png
    - assets/page-1/images/image-65.png
    - assets/page-1/images/image-41.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/image-67.png
    - assets/page-1/images/image-44.png
    - assets/page-1/images/image-27.png
    - assets/page-1/images/image-5-zL4.png
    - assets/page-1/images/image-52.png
    - assets/page-1/images/image-39.png
    - assets/page-1/images/image-43.png
    - assets/page-1/images/image-10.png
    - assets/page-1/images/image-43-Egk.png
    - assets/page-1/images/image-63.png
    - assets/page-1/images/image-23-suv.png
    - assets/page-1/images/image-133.png
    - assets/page-1/images/image-42-Qax.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/image-9-qwi.png
    - assets/page-1/images/image-31.png
    - assets/page-1/images/image-60.png
    - assets/page-1/images/image-133-w32.png
    - assets/page-1/images/image-17-Y7v.png
    - assets/page-1/images/image-7-mRv.png
    - assets/page-1/images/image-4-i6G.png
    - assets/page-1/images/image-13-uSt.png
    - assets/page-1/images/image-23-CMS.png
    - assets/page-1/images/image-22.png
    - assets/page-1/images/image-53-1wJ.png
    - assets/page-1/images/image-22-duN.png
    - assets/page-1/images/image-19.png
    - assets/page-1/images/image-49-R5n.png
    - assets/page-1/images/image-19-nsN.png
    - assets/page-1/images/image-22-8Bn.png
    - assets/page-1/images/image-19-usz.png
    - assets/page-1/images/image-51-ARA.png
    - assets/page-1/images/image-14-kMz.png
    - assets/page-1/images/image-46-ZDW.png
    - assets/page-1/images/image-53-LRr.png
    - assets/page-1/images/image-61.png
    - assets/page-1/images/image-43-5Wt.png
    - assets/page-1/images/image-50.png
    - assets/page-1/images/image-9-XV6.png
    - assets/page-1/images/image-51-Ar8.png
    - assets/page-1/images/image-55.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/image-69-LBN.png
    - assets/page-1/images/image-8.png
    - assets/page-1/images/image-66-1oi.png
    - assets/page-1/images/image-48-kPv.png
    - assets/page-1/images/image-36.png
    - assets/page-1/images/image-8-J8U.png
    - assets/page-1/images/image-35.png
    - assets/page-1/images/image-67-dTi.png
    - assets/page-1/images/image-23-aNx.png
    - assets/page-1/images/image-41-fo2.png
    - assets/page-1/images/ellipse-10.png
    - assets/page-1/images/image-47.png
    - assets/page-1/images/image-4-Koz.png
    - assets/page-1/images/image-60-kNp.png
    - assets/page-1/images/image-46-RDv.png
    - assets/page-1/images/image-45.png
    - assets/page-1/images/image-65-cpC.png
    - assets/page-1/images/image-44-y8x.png
    - assets/page-1/images/image-28.png
    - assets/page-1/images/image-46-SoE.png
    - assets/page-1/images/image-49-w3A.png
    - assets/page-1/images/image-63-C12.png
    - assets/page-1/images/image-54.png
    - assets/page-1/images/image-70.png
    - assets/page-1/images/image-55-kdz.png
    - assets/page-1/images/image-63-JcC.png
    - assets/page-1/images/image-43-Dz4.png
    - assets/page-1/images/image-43-RCx.png
    - assets/page-1/images/image-68.png
    - assets/page-1/images/image-20.png
    - assets/page-1/images/group-1-9mn.png
    - assets/page-1/images/image-83.png
    - assets/page-1/images/image-20-V1e.png
    - assets/page-1/images/image-30.png
    - assets/page-1/images/image-10-Guz.png
    - assets/page-1/images/image-84.png
    - assets/page-1/images/image-68-VRE.png
    - assets/page-1/images/image-85.png
    - assets/page-1/images/image-55-b3S.png
    - assets/page-1/images/image-41-5UQ.png
    - assets/page-1/images/image-48-tMJ.png
    - assets/page-1/images/image-71.png
    - assets/page-1/images/image-46-opx.png
    - assets/page-1/images/image-53-NqS.png
    - assets/page-1/images/image-80.png
    - assets/page-1/images/image-77.png
    - assets/page-1/images/image-58.png
    - assets/page-1/images/ellipse-13.png
    - assets/page-1/images/image-67-N6p.png
    - assets/page-1/images/image-49-Z9v.png
    - assets/page-1/images/image-21.png
    - assets/page-1/images/image-21-XNU.png
    - assets/page-1/images/image-21-v3E.png
    - assets/page-1/images/image-46-ipc.png
    - assets/page-1/images/image-76.png
    - assets/page-1/images/image-81.png
    - assets/page-1/images/image-46-Hpx.png
    - assets/page-1/images/image-46-8p4.png
    - assets/page-1/images/image-48-teg.png
    - assets/page-1/images/image-77-25z.png
    - assets/page-1/images/image-99.png
    - assets/page-1/images/image-92.png
    - assets/page-1/images/image-79.png
    - assets/page-1/images/image-78.png
    - assets/page-1/images/image-78-FD6.png
    - assets/page-1/images/image-104.png
    - assets/page-1/images/image-93.png
    - assets/page-1/images/image-62.png
    - assets/page-1/images/image-98.png
    - assets/page-1/images/image-46-ej6.png
    - assets/page-1/images/image-75.png
    - assets/page-1/images/image-102.png
    - assets/page-1/images/image-90.png
    - assets/page-1/images/image-95.png
    - assets/page-1/images/image-42-U1A.png
    - assets/page-1/images/image-96.png
    - assets/page-1/images/image-46-zAG.png
    - assets/page-1/images/image-86.png
    - assets/page-1/images/image-23-qi4.png
    - assets/page-1/images/image-77-k7E.png
    - assets/page-1/images/image-73-bg.png
    - assets/page-1/images/image-77-cuS.png
    - assets/page-1/images/image-46-bic.png
    - assets/page-1/images/image-46-xqi.png
    - assets/page-1/images/image-101.png
    - assets/page-1/images/image-105.png
    - assets/page-1/images/image-28-fTa.png
    - assets/page-1/images/image-115.png
    - assets/page-1/images/image-110.png
    - assets/page-1/images/image-111.png
    - assets/page-1/images/image-46-Hbr.png
    - assets/page-1/images/image-89.png
    - assets/page-1/images/image-117.png
    - assets/page-1/images/image-114.png
    - assets/page-1/images/image-120.png
    - assets/page-1/images/image-88.png
    - assets/page-1/images/image-88-3NU.png
    - assets/page-1/images/image-118.png
    - assets/page-1/images/image-124.png
    - assets/page-1/images/image-89-KEc.png
    - assets/page-1/images/image-119.png
    - assets/page-1/images/image-93-292.png
    - assets/page-1/images/image-74.png
    - assets/page-1/images/image-121.png
    - assets/page-1/images/image-89-E8c.png
    - assets/page-1/images/image-91.png
    - assets/page-1/images/image-90-9EU.png
    - assets/page-1/images/image-90-cKe.png
    - assets/page-1/images/image-77-7De.png
    - assets/page-1/images/image-4-zT6.png
    - assets/page-1/images/image-46-kZz.png
    - assets/page-1/images/image-113.png
    - assets/page-1/images/image-33-t68.png
    - assets/page-1/images/image-46-E9z.png
    - assets/page-1/images/image-32-Xet.png
    - assets/page-1/images/image-77-hJU.png
    - assets/page-1/images/ellipse-11.png
    - assets/page-1/images/image-127.png
    - assets/page-1/images/image-116.png
    - assets/page-1/images/image-112.png
    - assets/page-1/images/image-90-MC8.png
    - assets/page-1/images/image-46-5ic.png
    - assets/page-1/images/image-128.png
    - assets/page-1/images/image-126.png
    - assets/page-1/images/image-89-QoN.png
    - assets/page-1/images/image-88-tnx.png
    - assets/page-1/images/image-91-QnY.png
    - assets/page-1/images/image-4-6hA.png
    - assets/page-1/images/image-77-rRz.png
    - assets/page-1/images/image-31-gSp.png
    - assets/page-1/images/image-129.png
    - assets/page-1/images/ellipse-12.png
    - assets/page-1/images/image-123.png
    - assets/page-1/images/image-92-dsA.png
    - assets/page-1/images/image-65-NzG.png
    - assets/page-1/images/image-88-FnC.png
    - assets/page-1/images/image-46-VTa.png
    - assets/page-1/images/image-77-Mbr.png
    - assets/page-1/images/image-46-fkG.png
    - assets/page-1/images/image-92-nF6.png
    - assets/page-1/images/image-122.png
    - assets/page-1/images/image-89-356.png
    - assets/page-1/images/image-132.png
    - assets/page-1/images/image-66-fvC.png
    - assets/page-1/images/image-46-oRN.png
    - assets/page-1/images/image-78-t1J.png
    - assets/page-1/images/image-125.png
    - assets/page-1/images/image-77-9u6.png
    - assets/page-1/images/image-93-sME.png
    - assets/page-1/images/image-131.png
    - assets/page-1/images/image-46-Erp.png
    - assets/page-1/images/image-46-3dE.png
    - assets/page-1/images/image-68-9dv.png
    - assets/page-1/images/image-48-DDe.png
    - assets/page-1/images/image-46-ik4.png
    - assets/page-1/images/image-46-tcL.png
    - assets/page-1/images/image-130.png
    - assets/page-1/images/image-90-Lui.png
    - assets/page-1/images/image-92-uNU.png
    - assets/page-1/images/image-91-uoS.png
    - assets/page-1/images/image-48-V4G.png
    - assets/page-1/images/image-78-HCG.png
    - assets/page-1/images/image-4-86x.png
    - assets/page-1/images/image-66-ect.png
    - assets/page-1/images/image-60-GAQ.png
    - assets/page-1/images/image-46-fBi.png
    - assets/page-1/images/image-46-r8t.png
    - assets/page-1/images/image-34-nKN.png
    - assets/page-1/images/image-46-R5N.png
    - assets/page-1/images/image-77-UgC.png
    - assets/page-1/images/image-46-qLp.png
    - assets/page-1/images/image-69-wVe.png
    - assets/page-1/images/image-65-sTA.png
    - assets/page-1/images/image-46-9Lp.png
    - assets/page-1/images/image-77-1A4.png
    - assets/page-1/images/image-110-6uJ.png
    - assets/page-1/images/image-46-fLx.png
    - assets/page-1/images/image-46-Y9r.png
    - assets/page-1/images/image-77-qek.png
    - assets/page-1/images/image-112-Xgx.png
    - assets/page-1/images/image-46-tGc.png
    - assets/page-1/images/image-77-UEp.png
    - assets/page-1/images/image-46-Fw2.png
    - assets/page-1/images/image-65-zNp.png
    - assets/page-1/images/image-9-dAt.png
    - assets/page-1/images/image-60-7Q8.png
    - assets/page-1/images/image-77-2Ct.png
    - assets/page-1/images/image-46-y88.png
    - assets/page-1/images/image-66-Khn.png
    - assets/page-1/images/image-77-cgt.png
    - assets/page-1/images/image-46-sek.png
    - assets/page-1/images/image-62-pLL.png
    - assets/page-1/images/image-60-fsJ.png
    - assets/page-1/images/image-69-G7v.png
    - assets/page-1/images/image-46-8FW.png
    - assets/page-1/images/image-46-96C.png
    - assets/page-1/images/image-77-g9z.png
    - assets/page-1/images/image-77-t36.png
    - assets/page-1/images/image-68-RSC.png
    - assets/page-1/images/image-77-kdA.png
    - assets/page-1/images/image-77-vtU.png
    - assets/page-1/images/image-46-fyn.png
    - assets/page-1/images/image-80-zRi.png
    - assets/page-1/images/image-111-jhe.png
    - assets/page-1/images/image-77-Pit.png
    - assets/page-1/images/image-79-RG8.png
    - assets/page-1/images/image-46-nPW.png
    - assets/page-1/images/image-77-L3e.png
    - assets/page-1/images/image-46-qhe.png
    - assets/page-1/images/image-77-vzY.png
    - assets/page-1/images/image-123-6dz.png
    - assets/page-1/images/image-46-6JQ.png
    - assets/page-1/images/image-46-USg.png
    - assets/page-1/images/image-46-VFA.png
    - assets/page-1/images/image-46-NHS.png
    - assets/page-1/images/image-77-8wv.png
    - assets/page-1/images/image-46-e8t.png
    - assets/page-1/images/image-130-qLG.png
    - assets/page-1/images/image-77-UbW.png
    - assets/page-1/images/image-118-rWp.png
    - assets/page-1/images/image-66-g5A.png
    - assets/page-1/images/image-77-GEx.png
    - assets/page-1/images/image-46-9dW.png
    - assets/page-1/images/image-114-Q9z.png
    - assets/page-1/images/image-77-NgU.png
    - assets/page-1/images/image-46-5HE.png
    - assets/page-1/images/image-131-ioE.png
    - assets/page-1/images/image-77-tVz.png
    - assets/page-1/images/image-116-x5r.png
    - assets/page-1/images/image-46-cwe.png
    - assets/page-1/images/image-65-nk4.png
    - assets/page-1/images/image-46-XYY.png
    - assets/page-1/images/image-46-BNC.png
    - assets/page-1/images/image-77-sDe.png
    - assets/page-1/images/image-46-Zzt.png
    - assets/page-1/images/image-122-R9v.png
    - assets/page-1/images/image-120-r2G.png
    - assets/page-1/images/image-77-nxc.png
    - assets/page-1/images/image-124-k8k.png
    - assets/page-1/images/image-77-J4C.png
    - assets/page-1/images/image-46-gbe.png
    - assets/page-1/images/image-81-Ffz.png
    - assets/page-1/images/image-77-WNx.png
    - assets/page-1/images/image-77-t7v.png
    - assets/page-1/images/image-77-zAp.png
    - assets/page-1/images/image-77-1ZW.png
    - assets/page-1/images/image-129-9vc.png
    - assets/page-1/images/image-46-vAg.png
    - assets/page-1/images/image-121-EJ8.png
    - assets/page-1/images/image-61-mDv.png
    - assets/page-1/images/image-46-UNY.png
    - assets/page-1/images/image-46-RBJ.png
    - assets/page-1/images/image-77-3iU.png
    - assets/page-1/images/image-46-fdN.png
    - assets/page-1/images/image-46-daC.png
    - assets/page-1/images/image-77-bJ4.png
    - assets/page-1/images/image-50-XB2.png
    - assets/page-1/images/image-46-oiC.png
    - assets/page-1/images/image-46-PXJ.png
    - assets/page-1/images/image-46-LSY.png
    - assets/page-1/images/image-76-AyJ.png
    - assets/page-1/images/image-46-XYx.png
    - assets/page-1/images/image-46-gwe.png
    - assets/page-1/images/image-77-5Jt.png
    - assets/page-1/images/image-85-eWQ.png
    - assets/page-1/images/image-46-58Q.png
    - assets/page-1/images/image-77-gh2.png
    - assets/page-1/images/image-60-JTN.png
    - assets/page-1/images/image-77-7xY.png
    - assets/page-1/images/image-46-2rQ.png
    - assets/page-1/images/image-77-iZA.png
    - assets/page-1/images/image-40-Zfa.png
    - assets/page-1/images/image-119-VBS.png
    - assets/page-1/images/image-127-YoN.png
    - assets/page-1/images/image-74-6Hr.png
    - assets/page-1/images/image-77-s2L.png
    - assets/page-1/images/image-128-gG4.png
    - assets/page-1/images/image-46-4GC.png
    - assets/page-1/images/image-126-z3N.png
    - assets/page-1/images/image-125-rCk.png
    - assets/page-1/images/image-46-m2k.png
    - assets/page-1/images/image-46-ReU.png
    - assets/page-1/images/image-132-R1E.png